version: '3.7'

services:
    dbt:
        image: "ghcr.io/dbt-labs/dbt-postgres:1.3.1"
        volumes:
            - "./:/usr/app/dbt"
            - "./profiles.yml:/root/.dbt/profiles.yml"
        command: "run --vars='{\"table_prefix\":\"_09f85ac9\",\"timestamp\":\"1674902643.235171\",\"workspace_id\":\"1202473904551670\",\"integration_id\":\"09f85ac9-3404-4711-be2f-6d0f1f8f23af\"}'"
        networks:
            default:
            db-bridge:
                aliases: 
                    - db
networks:
    db-bridge:
        name: db-bridge
        driver: bridge
