version: '3.7'

services:
    dbt:
        image: "ghcr.io/dbt-labs/dbt-postgres:1.3.1"
        volumes:
            - "./:/usr/app/dbt"
            - "./profiles.yml:/root/.dbt/profiles.yml"
        command: "run --vars='{\"table_prefix\":\"_0dad819a\",\"timestamp\":\"1695634148.2174892\",\"workspace_id\":\"munityapps\",\"integration_id\":\"0dad819a-9535-44a3-b570-87dd1ac8eeaf\"}'"
        networks:
            default:
            db-bridge:
                aliases: 
                    - db
networks:
    db-bridge:
        name: db-bridge
        driver: bridge
